### ISSUE TITLE
Roadmap Beta 0.1.0

### ISSUE THREAD

**Issue by akazorg** [launcher-host/mercurius#8]
Roadmap features for the beta version 0.1.0:
- [ ] Unit tests
- [ ] Typing indicator
- [ ] Broadcast user status (when he goes on/off)
- [ ] Conversation with multiple users
- [ ] Search in messages content
- [ ] Upload photos and attach files
- [ ] Preview images and videos
- [ ] Emoji support
- [ ] Video Chat
- [ ] Support socket.io
- [ ] Web Hooks
